#!/usr/bin/env node
// Point a consumer project at this checkout's packages instead of npm, so a
// change can be exercised end to end (typecheck, tests, a dev deploy) before
// anything is published.
//
//   node scripts/link-service.mjs link    [dir ...]
//   node scripts/link-service.mjs unlink  [dir ...]
//   node scripts/link-service.mjs status  [dir ...]
//
// Default targets are the yyt service repo and its two examples, which are
// separate pnpm projects. `link` appends a marked `overrides:` block with
// `"@yingyeothon/<pkg>": "link:<relative path>"` for every package here to the
// target's `pnpm-workspace.yaml` (pnpm 11 reads overrides only from there)
// and runs `pnpm install`; `unlink` removes exactly that block and installs
// again. Consumers see each package's `dist`, so run `pnpm build` here after
// every change.
//
// The block and the lockfile churn it causes must not be committed in the
// consumer repo; `unlink` before committing there.
import { execFileSync } from "node:child_process";
import { existsSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { homedir } from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";

const tslibRoot = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  "..",
);
const serviceRoot = path.join(homedir(), "git", "yyt.life", "service");
const defaultTargets = [
  serviceRoot,
  path.join(serviceRoot, "examples", "sample-dungeon"),
  path.join(serviceRoot, "examples", "sample-morpg"),
];

const BEGIN =
  "# link-service:begin (generated by tslib/scripts/link-service.mjs)";
const END = "# link-service:end";

const [command = "status", ...dirs] = process.argv.slice(2);
if (!["link", "unlink", "status"].includes(command)) {
  console.error(`usage: link-service.mjs <link|unlink|status> [dir ...]`);
  process.exit(2);
}
const targets = (dirs.length > 0 ? dirs : defaultTargets).map((dir) =>
  path.resolve(dir),
);

const packages = readdirSync(path.join(tslibRoot, "packages"))
  .map((name) => path.join(tslibRoot, "packages", name))
  .filter((dir) => existsSync(path.join(dir, "package.json")))
  .map((dir) => ({
    name: JSON.parse(readFileSync(path.join(dir, "package.json"), "utf8")).name,
    dir,
  }));

function stripBlock(yaml) {
  const begin = yaml.indexOf(BEGIN);
  if (begin < 0) {
    return { yaml, linked: false };
  }
  const end = yaml.indexOf(END, begin);
  if (end < 0) {
    throw new Error(`unterminated link-service block`);
  }
  const before = yaml.slice(0, begin).replace(/\n+$/, "\n");
  const after = yaml.slice(end + END.length).replace(/^\n+/, "");
  return { yaml: before + after, linked: true };
}

for (const target of targets) {
  const workspacePath = path.join(target, "pnpm-workspace.yaml");
  if (!existsSync(workspacePath)) {
    console.error(`skip ${target}: no pnpm-workspace.yaml`);
    continue;
  }
  const original = readFileSync(workspacePath, "utf8");
  const { yaml: stripped, linked } = stripBlock(original);

  if (command === "status") {
    console.log(`${target}: ${linked ? "linked to tslib" : "npm"}`);
    continue;
  }
  if (command === "link" && /^overrides:/m.test(stripped)) {
    console.error(
      `skip ${target}: pnpm-workspace.yaml already has an overrides: key; merge by hand`,
    );
    continue;
  }

  let next = stripped;
  if (command === "link") {
    const lines = packages.map(
      ({ name, dir }) => `  "${name}": "link:${path.relative(target, dir)}"`,
    );
    next = `${stripped.replace(/\n*$/, "\n")}${BEGIN}\noverrides:\n${lines.join("\n")}\n${END}\n`;
  }
  if (next === original) {
    console.log(`${command}: ${target} (already)`);
    continue;
  }
  writeFileSync(workspacePath, next);
  console.log(`${command}: ${target}`);
  execFileSync("pnpm", ["install"], { cwd: target, stdio: "inherit" });
}

if (command === "link") {
  console.log(
    "\nLinked. Consumers resolve each package's dist: run `pnpm build` in tslib after every change.\n" +
      "Do not commit the pnpm-workspace.yaml / lockfile changes in the consumer; run `unlink` first.",
  );
}
